/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/layout/AdminHeader.vue')['default']
    AdminMenu: typeof import('./src/components/layout/AdminMenu.vue')['default']
    LoginFrom: typeof import('./src/components/auth/LoginFrom.vue')['default']
    RegisterFrom: typeof import('./src/components/auth/RegisterFrom.vue')['default']
    ResetPasswordFrom: typeof import('./src/components/auth/ResetPasswordFrom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
