/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/layout/AdminHeader.vue')['default']
    AdminHome: typeof import('./src/components/home/AdminHome.vue')['default']
    AdminMenu: typeof import('./src/components/layout/AdminMenu.vue')['default']
    AdminOverview: typeof import('./src/components/home/adminHome/AdminOverview.vue')['default']
    AdminUsers: typeof import('./src/components/users/AdminUsers.vue')['default']
    BarChart: typeof import('./src/components/home/adminHome/BarChart.vue')['default']
    Child: typeof import('./src/components/users/Child.vue')['default']
    Child1: typeof import('./src/components/users/Child1.vue')['default']
    CommmentManage: typeof import('./src/components/comment/CommmentManage.vue')['default']
    copy: typeof import('./src/components/users/Child copy.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    FriendList: typeof import('./src/components/friends/FriendList.vue')['default']
    LineChart: typeof import('./src/components/home/adminHome/LineChart.vue')['default']
    LoginFrom: typeof import('./src/components/auth/LoginFrom.vue')['default']
    ManageNote: typeof import('./src/components/notes/manageNote/ManageNote.vue')['default']
    ManageTag: typeof import('./src/components/notes/manageTag/ManageTag.vue')['default']
    ManageType: typeof import('./src/components/notes/manageType/ManageType.vue')['default']
    NoteManage: typeof import('./src/components/notes/manageNote/NoteManage.vue')['default']
    PersonalManage: typeof import('./src/components/personalCenter/personalManage.vue')['default']
    PieChart: typeof import('./src/components/home/adminHome/PieChart.vue')['default']
    RegisterFrom: typeof import('./src/components/auth/RegisterFrom.vue')['default']
    ResetPasswordFrom: typeof import('./src/components/auth/ResetPasswordFrom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagManage: typeof import('./src/components/notes/manageTag/TagManage.vue')['default']
    TypeManage: typeof import('./src/components/notes/manageType/TypeManage.vue')['default']
    Write: typeof import('./src/components/notes/manageWrite/Write.vue')['default']
    WriteFriend: typeof import('./src/components/friends/WriteFriend.vue')['default']
  }
}
